### ISSUE TITLE
[Bug] r.learn.ml- onehot encoding  not working any more with  scikit-learn 0.22

### ISSUE THREAD

**Issue by maitlang1** [OSGeo/grass-addons#103] opened 2020-02-26 13:08 UTC
**Name of the addon**
 r.learn.m

**Describe the bug**
In the new scikit-learn 0.22 the OneHotEncode() function parameters are changed and category maps can not be used in   r.learn.m current version.

**To Reproduce**
Test with category maps. 

**Expected behavior**

Error message here
clf = Pipeline([('onehot', OneHotEncoder(
                categorical_features=categorymaps

**System description (please complete the following information):**
 - Operating System: OpenSUSE Leap 15.1
 - GRASS GIS version  7.9.dev
-  python 3

**Additional context**
There is a new version of r.learn.ml (separate train and predict modules) in github where the problem is solved.  In this version (training and predicting in one module) the message could be modified to indicate the last version of python3-scikit-learn  that is compatible with the script: 
gs.fatal("Package python3-scikit-learn 0.18 or newer is not installed") .

I have not tested with python3-scikit-learn <0.22.

**Comment by veroandreo** [comment] 2020-02-26 13:15
> **Name of the addon**
> r.learn.m
> 
> **Describe the bug**
> In the new scikit-learn 0.22 the OneHotEncode() function parameters are changed and category maps can not be used in r.learn.m current version.
> 
> **To Reproduce**
> Test with category maps.

Please provide a set of commands to reproduce (you can use the example in the manual as a basis)

> **Expected behavior**
> 
> Error message here
> clf = Pipeline([('onehot', OneHotEncoder(
> categorical_features=categorymaps
 
> **Additional context**
> There is a new version of r.learn.ml (separate train and predict modules) in github where the problem is solved. In this version (training and predicting in one module) the message could be modified to indicate the last version of python3-scikit-learn that is compatible with the script:
> gs.fatal("Package python3-scikit-learn 0.18 or newer is not installed") .

Would you please provide the link where this new version of r.learn.ml exists?

**Comment by maitlang1** [comment] 2020-02-26 16:51
Sorry, forgot the link to Steve's repo: 
https://github.com/stevenpawley/r.learn.ml .

**Comment by neteler** [comment] 2020-02-26 17:49
Let's keep it open since the problem isn't solved yet

**Comment by neteler** [comment] 2020-03-18 20:12
note: @stevenpawley told me off-list that he prepares an update of r.learn.ml

**Comment by neteler** [comment] 2020-03-21 10:56
@maitlang1 could you give https://github.com/OSGeo/grass-addons/pull/126 a try (New version of r.learn.ml)?

**Comment by maitlang1** [comment] 2020-03-23 16:51
GRASS 7.9.dev (25m_raster):~ > g.extension -s r.learn.ml url=github.com/stevenpawley/r.learn.ml
WARNING: Extension <r.learn.ml> already installed. Re-installing...
Fetching <r.learn.ml> from
<https://github.com/stevenpawley/r.learn.ml/archive/master.zip> (be
patient)...
Compiling...
Installing...
Updating private addons metadata file...
WARNING: No addons metadata available. Addons metadata file not updated.
Installation of <r.learn.ml> successfully finished


The test
-----------
Extracting training data
Traceback (most recent call last):
  File "/usr/local/grass79/scripts/r.learn.train", line 876,
in <module>
    main()
  File "/usr/local/grass79/scripts/r.learn.train", line 588,
in main
    X, y, cat = stack.extract_points(training_points, field)
  File "/usr/local/grass79/etc/r.learn.ml/raster.py", line
886, in extract_points
    self._grass_sql_dtype_to_numpy(df_cols[field])
  File "/usr/local/grass79/etc/r.learn.ml/raster.py", line
815, in _grass_sql_dtype_to_numpy
    return grass_vector_dtypes[dtype]
KeyError: 'int'


The response column description: 
column:PE
description:
type:INTEGER
len:20
scale:0
precision:0
default:
nullok:yes
select:?
update:?

**Comment by stevenpawley** [comment] 2020-03-23 18:06
Thanks for this, it should be fixed now in 0aa72e9

**Comment by maitlang1** [comment] 2020-03-24 12:19
I compiled a grass database for testing r.learn.ml addon: https://drive.google.com/file/d/1wQEwJNKtFheD5cBoXQwdiuBaqk1bI-25/view?usp=sharing . The database structure description is included.

**Comment by stevenpawley** [comment] 2020-05-29 05:35
I'm going to close this because I've switched all further work to r.learn.ml2

**Closed by stevenpawley** 2020-05-29 05:35 UTC
