### ISSUE TITLE
i.superpixel.slic extension not found

### ISSUE THREAD

**Issue by mkieser** [OSGeo/grass-addons#581] opened 2021-07-08 15:35 UTC
**Name of the addon**
i.superpixel.slic

**Describe the bug**
I run the `g.extension i.superpixels.slic` command and the URL `https://github.com/OSGeo/grass-addons/trunk/grass7/imagery/i.superpixels.slic` doesn't exist.
I've also tried the command with the full URL `g.extension i.superpixels.slic url="https://github.com/OSGeo/grass-addons/tree/grass7/src/imagery/i.superpixels.slic" branch="grass7"` and the extension is not found.

**To Reproduce**
1. Run ` g.extension i.superpixels.slic `
2. See erros
3. Run ` g.extension i.superpixels.slic url="https://github.com/OSGeo/grass-addons/tree/grass7/src/imagery/i.superpixels.slic" branch="grass7" `

**Expected behavior**
I expect that the i.superpixels.slic extension will be added from the GitHub URL

**Screenshots**
N/A

**System description (please complete the following information):**
 - Operating System: Docker container built from `FROM neteler/grassgis7`
 - GRASS GIS version 
 ```
version=8.0.dev
date=2021
revision=exported
build_date=2021-07-08
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2021-07-08T13:50:41+00:00
libgis_date=2021-07-08T13:50:41+00:00
proj=4.9.3
gdal=2.2.3
geos=3.6.2
sqlite=3.22.0
```

**Additional context**
N/A

**Comment by veroandreo** [comment] 2021-07-08 16:01
I'm experiencing the same with GRASS 7.8.5 (current stable) and grass dev recompiled as of today too. AFAIU the addon installation is failing since the re-structuring of grass-addons repo in #571.

But the problem is with `g.extension` that needs to be fixed accordingly and not the addons themselves. There's a draft PR that tackles this: https://github.com/OSGeo/grass/pull/1700

**Comment by ninsbl** [comment] 2021-07-08 22:59
The problem is probably that `grass7` now is the default branch (more than that the grass7 branch got restructured). "trunk" in the URL refers to the default branch.

When the branch concept got included in `g.extension`, unfortunately, `main` and `master` were treated as if they allways would be the default branches, which is what now causes trouble...

Will try to get #1700 ready to merge ASAP...

**Comment by tgrippa** [comment] 2021-07-12 14:34
Hi all, 
Same problem for me here. Do you know if the issue will be solved in 7.8.5 or I would have to use grass dev and compile myself when the source code will be fixed ? 
Thanks

**Comment by veroandreo** [comment] 2021-07-12 23:04
Grass 7.8.5 is the current stable and because of addon repo restructuring, g.extension is momentarily not working. It should be solved for 7.8.6, this is a blocker of the release indeed.

**Comment by carolxgl** [comment] 2021-07-15 16:39
Hi all,
I have the same problem when trying: g.extension r.forestfrag .

**Comment by wenzeslaus** [comment] 2021-07-20 02:11
If you are comfortable with JupyterLab you can test OSGeo/grass#1700 using Binder ([link](https://mybinder.org/v2/gh/ninsbl/grass/g_extension_version?urlpath=lab%2Ftree%2Fdoc%2Fnotebooks%2Fexample_notebook.ipynb)). Click _File > New > Terminal_ and type:

```
grass data/grassdata/nc_basic_spm_grass7/user1
```
```
g.extension r.clip
```

**Comment by ninsbl** [comment] 2021-07-21 14:47
FYI: https://github.com/OSGeo/grass/pull/1700 has been merged into master.

**Comment by ninsbl** [comment] 2022-09-24 20:16
I think this can be closed as fixed. Can you confirm @mkieser ?

**Closed** 2022-09-24 22:12 UTC
